### ISSUE TITLE
3.6절 키움증권 로그인 하기 단계에서 에러가 발생하여 문의 남깁니다.

### ISSUE THREAD

**Issue by adfhief** [papadaks/SystemTrading#2]
안녕하세요 쉽게 따라만드는 파이썬 주식 자동매매 시스템 독자입니다.
다름이 아니라 로그인 하기 단계에서 에러가 발생했는데 해결법을 찾을 수가 없어서 문의 남깁니다.

책에 나와있는데로 코드를 작성했는데

Traceback (most recent call last):
  File "C:/Users/emins/PycharmProjects/SystamTrading/main.py", line 6, in <module>
    kiwoom = Kiwoom()
  File "C:\Users\emins\PycharmProjects\SystamTrading\api\Kiwoom.py", line 11, in __init__
    self._set_signal_slots()
  File "C:\Users\emins\PycharmProjects\SystamTrading\api\Kiwoom.py", line 18, in _set_signal_slots
    self.OnEventConnect.connect(self._login_slot)
AttributeError: 'Kiwoom' object has no attribute 'OnEventConnect'

위와 같은 문구로 에러가 발생하였습니다. 어떻게 해결해야 할까요?

**Comment by papadaks** [comment]
안녕하세요 선생님
구매해주셔서 감사합니다.
해당 에러에 대해서는 다음 글에서 다룬 적이 있습니다.
참고해주시면 좋겠습니다
https://jsp-dev.tistory.com/284
