### ISSUE TITLE
해결방법 좀 알 수 있을까요?

### ISSUE THREAD

**Issue by gyuhoahn** [papadaks/SystemTrading#7]

**Comment by gyuhoahn** [comment]
> Traceback (most recent call last): File "C:/Users/PycharmProjects/SystemTrading-master/main.py", line 1, in from strategy.RSIStrategy import * File "C:\Users\PycharmProjects\SystemTrading-master\strategy\RSIStrategy.py", line 1, in from api.Kiwoom import * File "C:\Users\PycharmProjects\SystemTrading-master\api\Kiwoom.py", line 5, in import pandas as pd ModuleNotFoundError: No module named 'pandas'
> 
> 종료 코드 1(으)로 완료된 프로세스
